### ISSUE TITLE
Error when attempting to invite new user to development

### ISSUE THREAD

**Issue by scascarini** [MetalUp/Express#217]
Error message received from server
A software error has occurred on the server(InternalServerError(500))
Object reference not set to an instance of an object.

at Model.Menus.Activities.ActivitiesOfCurrentUser(IContext context) in C:\projects\express-wot3y\Administration System\Administration.Model\Menus\Activities.cs:line 64

at Model.Menus.Tasks.MyLastActiveTaskId(IContext context) in C:\projects\express-wot3y\Administration System\Administration.Model\Menus\Tasks.cs:line 27

at Model.Services.UserService.GetUser(IContext context) in C:\projects\express-wot3y\Administration System\Administration.Model\Services\UserService.cs:line 25

at NakedFramework.Core.Util.DelegateUtils.<>c__DisplayClass32_0`3.<StaticFuncHelper1>b__0(Object target, Object[] param)

at NakedFramework.Core.Util.DelegateUtils.<>c__DisplayClass8_0.<WrapException>b__0(Object target, Object[] param)

at NakedFramework.Core.Util.InvokeUtils.InvokeStatic[T](Func`3 methodDelegate, MethodInfo method, Object[] parms)

at NakedFramework.Metamodel.Serialization.MethodSerializationWrapper.Invoke[T](Object[] args)

**Comment by richardpawson** [comment]
Fixed
