### ISSUE TITLE
Login with existing user on invitation causes exception

### ISSUE THREAD

**Issue by scascarini** [MetalUp/Express#218]
Error message received from server
A software error has occurred on the server(InternalServerError(500))
Sequence contains more than one element

at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()

at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)

at lambda_method131(Closure , QueryContext )

at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)

at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)

at System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)

at Model.Menus.Users.Me(IContext context) in C:\projects\express-8ant5\Administration System\Administration.Model\Menus\Users.cs:line 11

at Model.Services.UserService.GetUser(IContext context) in C:\projects\express-8ant5\Administration System\Administration.Model\Services\UserService.cs:line 24

at NakedFramework.Core.Util.DelegateUtils.<>c__DisplayClass32_0`3.<StaticFuncHelper1>b__0(Object target, Object[] param)

at NakedFramework.Core.Util.DelegateUtils.<>c__DisplayClass8_0.<WrapException>b__0(Object target, Object[] param)

at NakedFramework.Core.Util.InvokeUtils.InvokeStatic[T](Func`3 methodDelegate, MethodInfo method, Object[] parms)

at NakedFramework.Metamodel.Serialization.MethodSerializationWrapper.Invoke[T](Object[] args)

at NakedFunctions.Reflector.Facet.ActionInvocationFacetViaStaticMethod.Invoke(INakedObjectAdapter inObjectAdapter, INakedObjectAdapter[] parameters, INakedFramework framework)

at NakedFramework.Core.Spec.ActionSpec.Execute(INakedObjectAdapter nakedObjectAdapter, INakedObjectAdapter[] parameterSet)

at NakedFramework.Facade.Impl.Impl.FrameworkFacade.ExecuteAction(ActionContext actionContext, ArgumentsContextFacade arguments)

at NakedFramework.Facade.Impl.Impl.FrameworkFacade.<>c__DisplayClass46_0.<ExecuteMenuAction>b__0()

at NakedFramework.Facade.Impl.Impl.FrameworkFacade.MapErrors[T](Func`1 f)

**Comment by richardpawson** [comment]
Please call me about this one when you are back.
   
   
   
    On 03/05/2023 10:30 BST Stefano Cascarini ***@***.***> wrote:
    
   
     
    
   
     
    
     
   Assigned #218 to @richardpawson.

**Comment by richardpawson** [comment]
Completed
